// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenHarbor.DAL;

#nullable disable

namespace OpenHarbor.DAL.Migrations
{
    [DbContext(typeof(PluginCatalogDbContext))]
    [Migration("20261005110958_Plugins")]
    partial class Plugins
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("OpenHarbor.Models.PluginRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DllRelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDashboardProvider")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelectedDashboardProvider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicFolderRelativePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteSubpath")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsSelectedDashboardProvider")
                        .IsUnique()
                        .HasFilter("[IsSelectedDashboardProvider] = 1");

                    b.HasIndex("RouteSubpath")
                        .IsUnique();

                    b.ToTable("Plugins");
                });
#pragma warning restore 612, 618
        }
    }
}
