import React from 'react';

export default React;
export {
	Activity,
	Children,
	Component,
	Fragment,
	Profiler,
	PureComponent,
	StrictMode,
	Suspense,
	ViewTransition,
	act,
	addTransitionType,
	cache,
	cacheSignal,
	captureOwnerStack,
	cloneElement,
	createContext,
	createElement,
	createRef,
	forwardRef,
	isValidElement,
	lazy,
	memo,
	startTransition,
	unstable_useCacheRefresh,
	use,
	useActionState,
	useCallback,
	useContext,
	useDebugValue,
	useDeferredValue,
	useEffect,
	useEffectEvent,
	useId,
	useImperativeHandle,
	useInsertionEffect,
	useLayoutEffect,
	useMemo,
	useOptimistic,
	useReducer,
	useRef,
	useState,
	useSyncExternalStore,
	useTransition,
	version,
} from 'react';
export { createPortal, flushSync } from 'react-dom';
export { createRoot } from 'react-dom/client';
export function PluginUiProvider(props: React.PropsWithChildren<{ components: Record<string, React.ComponentType<any>> }>): React.ReactElement;